# 使用基于 Ubuntu 22.04 的基础镜像
FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/ubuntu:22.04

# 设置工作目录
WORKDIR /app

# 安装必要的依赖
RUN apt-get update && apt-get install -y \
    curl \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# 安装 ODBC 驱动
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 \
    && rm -rf /var/lib/apt/lists/*

# 复制当前目录下的文件到工作目录
COPY . .

# 安装 Python 依赖
RUN pip3 config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
RUN pip3 install -r requirements.txt
RUN pip3 install uvicorn

# 暴露 Flask 应用的端口
EXPOSE 5001

# 启动 Python 脚本
CMD ["python3", "vanna_fastapi.py"]


